In [17]:
# import of important libraries
import numpy as np
import pandas as pd 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

### Import of dataset

In [18]:
dataset = load_breast_cancer()

In [19]:
# Put data in a pandas DataFrame
df_cancer = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df_cancer["target"] = dataset.target
df_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

### Seperation of features and target variable

In [20]:
X = df_cancer.iloc[:,:-1]
y = df_cancer.iloc[:,-1]

### Defining train test split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# scalar = StandardScaler()
# X_train = scalar.fit_transform(X_train)
# X_test = scalar.transform(X_test)

### Applying Logistic Regression with the help of sigmoid formula


- To find the coefficients C, we use the formular
$$
C = (X{train}^TX{train})^{-1}X{train}^TY{train}
$$

- Takes X_train and y_train training samples as an argument. 

- passing the arguments into the sigmoid function.
$$
\begin{equation}
Y_{score} = \frac{1}{1+e^{-XC}}
\end{equation}
$$
$$
\begin{equation}
Y{pred} = 0 \ if \ Y{score} \ < \ 0.5 \ else \ 1
\end{equation}
$$

- Calculates the cost and applies the gradient descent on the derivatives of the cost.
- Returns the weight and the costs.



sources:
1. https://www.hackerearth.com/practice/machine-learning/linear-regression/multivariate-linear-regression-1/tutorial/
2. https://realpython.com/logistic-regression-python/

In [35]:
# # Apply sigmoid function to limit the values between [0-1]
def sigmoid(scores):
    return 1 / (1 + np.exp(-scores))


In [23]:
def logistic_regression(X, y):
    iterations = 10000
    learning_rate = 0.0015
    costs= []
    weights = np.zeros(X.shape[1])
    for index in range(iterations):
        scores = np.dot(X, weights) 
        y_pred = sigmoid(scores)

        # cost calculates whether the actual values are predicted values or it has some loss while training
        cost = -(1/X.shape[0])*np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))

        # Applying Gradient Descent by calculating the derivatives of the cost to find the minimum point
        gradient_weight =  np.dot(X.T, y_pred - y) / X.shape[0]

        # Updating the weights after each iterations
        weights -= learning_rate * gradient_weight

        costs.append(cost)

    return weights, costs

In [24]:
# takes the testing data as an argument and returns the predicted outcomes 
def predict(X):
    weights = logistic_regression(X_train, y_train)[0]
    # Calculates the scores with training samples and weights)
    scores = np.dot(X, weights)
    pred = [1 if i > 0.5 else 0 for i in sigmoid(scores)]
    return np.array(pred)

In [25]:
predictions = predict(X_test)

<ipython-input-23-8ec746afe2b2>:10: RuntimeWarning: divide by zero encountered in log
  cost = -(1/X.shape[0])*np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))
<ipython-input-22-0c53d5774a4d>:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-scores))


In [26]:
predictions

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [27]:
# given y_test values
np.array(y_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [28]:
(predictions==y_test).mean()

0.8421052631578947

### Applying Logistic Regression from Library

In [29]:
model = LogisticRegression()
model.fit(X_train,y_train)

C:\Users\shahi\anaconda3\envs\strive\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
predi = model.predict(X_test)

In [31]:
predi

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [32]:
np.array(y_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [33]:
(predi==y_test).mean()

0.9649122807017544